import type { Job } from "@/types";

const slugify = (s: string) =>
  s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");

const formatDate = (iso: string) => {
  const d = new Date(iso);
  return d.toISOString().slice(2, 10).replace(/-/g, "-");
};

const formatTime = (iso?: string) => {
  if (!iso) return "—";
  return new Date(iso).toLocaleString("en-US", {
    month: "short", day: "numeric", year: "numeric",
    hour: "numeric", minute: "2-digit",
  });
};

async function imageToBase64(url: string): Promise<string> {
  try {
    const res = await fetch(url);
    const blob = await res.blob();
    return new Promise((resolve) => {
      const reader = new FileReader();
      reader.onloadend = () => resolve(reader.result as string);
      reader.readAsDataURL(blob);
    });
  } catch {
    return "";
  }
}

export async function generateHtmlReport(
  job: Job,
  onProgress?: (pct: number) => void
): Promise<{ html: string; filename: string }> {
  const description = job.description || "Photo Walk";
  const dateStr = formatDate(job.createdAt);
  const filename = `${dateStr}-${slugify(job.name)}-${slugify(description)}.html`;

  // Collect all photo URLs that need base64 conversion
  const allPins = job.floors.flatMap((f) => f.pins);
  const photoUrls = allPins.filter((p) => p.photoUrl).map((p) => p.photoUrl!);
  const totalPhotos = photoUrls.length;
  let converted = 0;

  // Convert all photos to base64
  const base64Map = new Map<string, string>();
  for (const url of photoUrls) {
    const b64 = await imageToBase64(url);
    base64Map.set(url, b64);
    converted++;
    onProgress?.(Math.round((converted / Math.max(totalPhotos, 1)) * 100));
  }

  const floorsHtml = job.floors
    .map((floor) => {
      const pinsHtml = floor.pins
        .map((pin) => {
          const photoSrc = pin.photoUrl ? base64Map.get(pin.photoUrl) || pin.photoUrl : "";
          return `
        <div style="border:1px solid #e2e8f0;border-radius:8px;overflow:hidden;margin-bottom:16px;">
          ${photoSrc ? `<img src="${photoSrc}" alt="${pin.name}" style="width:100%;max-height:300px;object-fit:cover;" />` : `<div style="height:120px;background:#f1f5f9;display:flex;align-items:center;justify-content:center;color:#94a3b8;font-size:14px;">No photo</div>`}
          <div style="padding:12px;">
            <div style="font-weight:600;font-size:15px;color:#1e293b;">${pin.name}</div>
            <div style="font-size:12px;color:#64748b;margin-top:4px;">Captured: ${formatTime(pin.capturedAt)}</div>
            ${pin.notes ? `<div style="margin-top:8px;font-size:13px;color:#475569;white-space:pre-wrap;background:#f8fafc;padding:8px;border-radius:4px;">${pin.notes}</div>` : ""}
          </div>
        </div>`;
        })
        .join("\n");

      const filled = floor.pins.filter((p) => p.photoUrl).length;
      return `
      <div style="margin-bottom:32px;">
        <h2 style="font-size:20px;font-weight:600;color:#1e293b;border-bottom:2px solid #3b82f6;padding-bottom:6px;margin-bottom:16px;">
          ${floor.name} <span style="font-weight:400;font-size:14px;color:#64748b;">(${filled}/${floor.pins.length} captured)</span>
        </h2>
        <div style="display:grid;grid-template-columns:repeat(auto-fill,minmax(280px,1fr));gap:16px;">
          ${pinsHtml || '<div style="color:#94a3b8;font-size:14px;">No pins on this floor.</div>'}
        </div>
      </div>`;
    })
    .join("\n");

  const totalFilled = allPins.filter((p) => p.photoUrl).length;

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>${job.name} — ${description}</title>
  <style>
    * { margin:0; padding:0; box-sizing:border-box; }
    body { font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif; background:#fff; color:#1e293b; padding:24px; max-width:1100px; margin:0 auto; }
    @media print { body { padding:12px; } }
  </style>
</head>
<body>
  <div style="border-bottom:3px solid #3b82f6;padding-bottom:16px;margin-bottom:24px;">
    <h1 style="font-size:26px;font-weight:700;color:#0f172a;">${job.name}</h1>
    <div style="margin-top:6px;font-size:14px;color:#64748b;">${description}</div>
    <div style="margin-top:4px;font-size:13px;color:#94a3b8;">
      Created: ${new Date(job.createdAt).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}
      &nbsp;•&nbsp; ${totalFilled}/${allPins.length} pins captured
      &nbsp;•&nbsp; ${job.floors.length} floor(s)
    </div>
  </div>

  ${floorsHtml}

  <div style="margin-top:32px;padding-top:16px;border-top:1px solid #e2e8f0;font-size:11px;color:#94a3b8;text-align:center;">
    Generated by Sitedochub &nbsp;•&nbsp; ${new Date().toLocaleString()} &nbsp;•&nbsp; Halsell Builders
  </div>
</body>
</html>`;

  return { html, filename };
}

export function downloadHtmlReport(html: string, filename: string) {
  const blob = new Blob([html], { type: "text/html;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
